package com.allybros.elephant.util


/**
 * Created by orcun on 4.03.2023
 */

const val INTENT_EXTRA_TITLE = "INTENT_TITLE"
const val INTENT_EXTRA_DESCRIPTION = "INTENT_DESCRIPTION"
const val TITLE = "Elephant"
const val NOTIFICATION_DESCRIPTION = "ELEPHANT_NOTIFICATION_CHANNEL"
const val NOTIFICATION_CHANNEL_ID = "ELEPHANT"
const val NOTIFICATION_CHANNEL_NAME = "ELEPHANT_CHANNEL"
